// Code generated by Wire protocol buffer compiler, do not edit.
// Source: Favourite in Favourites.proto
package com.cniekirk.traintimes.model

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class Favourite(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val fromCrs: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val fromStationName: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val toCrs: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  val toStationName: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : AndroidMessage<Favourite, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Favourite) return false
    if (unknownFields != other.unknownFields) return false
    if (fromCrs != other.fromCrs) return false
    if (fromStationName != other.fromStationName) return false
    if (toCrs != other.toCrs) return false
    if (toStationName != other.toStationName) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + fromCrs.hashCode()
      result = result * 37 + fromStationName.hashCode()
      result = result * 37 + toCrs.hashCode()
      result = result * 37 + toStationName.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """fromCrs=${sanitize(fromCrs)}"""
    result += """fromStationName=${sanitize(fromStationName)}"""
    result += """toCrs=${sanitize(toCrs)}"""
    result += """toStationName=${sanitize(toStationName)}"""
    return result.joinToString(prefix = "Favourite{", separator = ", ", postfix = "}")
  }

  fun copy(
    fromCrs: String = this.fromCrs,
    fromStationName: String = this.fromStationName,
    toCrs: String = this.toCrs,
    toStationName: String = this.toStationName,
    unknownFields: ByteString = this.unknownFields
  ): Favourite = Favourite(fromCrs, fromStationName, toCrs, toStationName, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<Favourite> = object : ProtoAdapter<Favourite>(
      FieldEncoding.LENGTH_DELIMITED, 
      Favourite::class, 
      "type.googleapis.com/Favourite", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: Favourite): Int {
        var size = value.unknownFields.size
        if (value.fromCrs != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.fromCrs)
        if (value.fromStationName != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2,
            value.fromStationName)
        if (value.toCrs != "") size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.toCrs)
        if (value.toStationName != "") size += ProtoAdapter.STRING.encodedSizeWithTag(4,
            value.toStationName)
        return size
      }

      override fun encode(writer: ProtoWriter, value: Favourite) {
        if (value.fromCrs != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.fromCrs)
        if (value.fromStationName != "") ProtoAdapter.STRING.encodeWithTag(writer, 2,
            value.fromStationName)
        if (value.toCrs != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.toCrs)
        if (value.toStationName != "") ProtoAdapter.STRING.encodeWithTag(writer, 4,
            value.toStationName)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): Favourite {
        var fromCrs: String = ""
        var fromStationName: String = ""
        var toCrs: String = ""
        var toStationName: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> fromCrs = ProtoAdapter.STRING.decode(reader)
            2 -> fromStationName = ProtoAdapter.STRING.decode(reader)
            3 -> toCrs = ProtoAdapter.STRING.decode(reader)
            4 -> toStationName = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Favourite(
          fromCrs = fromCrs,
          fromStationName = fromStationName,
          toCrs = toCrs,
          toStationName = toStationName,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: Favourite): Favourite = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    val CREATOR: Parcelable.Creator<Favourite> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
